name: Push to Prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p 4501 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Test SSH login (password)
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          ssh -p 4501 \
          -o PreferredAuthentications=password \
          -o PubkeyAuthentication=no \
          -o StrictHostKeyChecking=yes \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "whoami && pwd"

      - name: Deploy with rsync using password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          rsync -avuz -P --exclude=".*" \
          -e "ssh -p 4501 -o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=yes" \
          . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/vhosts/berh.com.br/httpdocs/admin/

      - name: Install composer and run migration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 4501
          script: |
            cd /var/www/vhosts/berh.com.br/httpdocs/admin/
            php -v
            php composer.phar install --no-dev --prefer-dist --optimize-autoloader
            vendor/bin/phinx migrate -e production
